# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

eth2stats:
  addr: "localhost:9090"
  node-name: "test"
  tls: true

beacon:
  # Beacon node type [supported: prysm]
  type: "prysm"

  # Beacon node endpoint address
  addr: "localhost:8545"

  # The url where the beacon client exposes metrics (used for memory usage)
  metrics-addr: "http://localhost:8080/metrics"