# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

eth2stats:
  addr: "localhost:9090"
  node-name: "test"
  tls: true

beacon:
  type: "prysm"
  addr: "localhost:8545"