#!/bin/bash
# use manifest-tool to create the manifest
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/latest/download/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-args --platforms linux/amd64,linux/arm64 --template ${IMAGE_NAME}-ARCH --target ${IMAGE_NAME}
./manifest-tool push from-args --platforms linux/amd64,linux/arm64 --template ${IMAGE_NAME}-ARCH --target ${DOCKER_REPO}:latest